[package]
name = "ac-formats"
description = "Decoders for the asset types stored in Asheron's Call DAT archives"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glam = { workspace = true, features = ["serde"] }
serde.workspace = true
thiserror.workspace = true
image = { workspace = true, features = ["jpeg"] }

[dev-dependencies]
ac-dat = { path = "../ac-dat" }
