//! Text for the server's WeenieError (0x028A) and WeenieErrorWithString
//! (0x028B) codes. The retail client read these from its language DAT;
//! the test server ships none, so the codes are named after ACE's enum
//! identifiers rendered as sentences. `{}` is the string parameter.
//!
//! Not every refusal comes as a code. Recruiting into a fellowship
//! someone already in one, or busy, is answered in plain Broadcast chat
//! ("{Name} is already a member of a Fellowship.", "{Name} is busy.";
//! ACE `Entity/Fellowship.cs`), which `ac_client::autoplay` reads as
//! words.

/// Message for a WeenieError code, or None for codes with no text.
pub fn text(code: u32) -> Option<&'static str> {
    PLAIN
        .binary_search_by_key(&code, |e| e.0)
        .ok()
        .map(|i| PLAIN[i].1)
}

/// Message for a WeenieErrorWithString code with its parameter filled in.
pub fn text_with(code: u32, param: &str) -> Option<String> {
    WITH.binary_search_by_key(&code, |e| e.0)
        .ok()
        .map(|i| WITH[i].1.replace("{}", param))
}

static PLAIN: [(u32, &str); 368] = [
    (0x0001, "No mem"),
    (0x0002, "Bad param"),
    (0x0003, "Div zero"),
    (0x0004, "Seg v"),
    (0x0005, "Unimplemented"),
    (0x0006, "Unknown message type"),
    (0x0007, "No animation table"),
    (0x0008, "No physics object"),
    (0x0009, "No bookie object"),
    (0x000a, "No wsl object"),
    (0x000b, "No motion interpreter"),
    (0x000c, "Unhandled switch"),
    (0x000d, "Default constructor called"),
    (0x000e, "Invalid combat maneuver"),
    (0x000f, "Bad cast"),
    (0x0010, "Missing quality"),
    (0x0012, "Missing database object"),
    (0x0013, "No callback set"),
    (0x0014, "Corrupt quality"),
    (0x0015, "Bad context"),
    (0x0016, "No ephseq manager"),
    (0x0017, "Bad movement event"),
    (0x0018, "Cannot create new object"),
    (0x0019, "No controller object"),
    (0x001a, "Cannot send event"),
    (0x001b, "Physics can't transition"),
    (0x001c, "Physics max distance exceeded"),
    (0x001d, "You're too busy"),
    (0x001f, "Cannot send message"),
    (0x0020, "Illegal inventory transaction"),
    (0x0021, "External weenie object"),
    (0x0022, "Internal weenie object"),
    (0x0023, "Motion failure"),
    (0x0024, "You can't jump while in the air"),
    (0x0025, "Inq cyl sphere failure"),
    (0x0026, "That is not a valid command"),
    (0x0027, "Carrying item"),
    (0x0028, "Frozen"),
    (0x0029, "Stuck"),
    (0x002a, "You are too encumbered"),
    (0x002c, "Bad contain"),
    (0x002d, "Bad parent"),
    (0x002e, "Bad drop"),
    (0x002f, "Bad release"),
    (0x0030, "Msg bad msg"),
    (0x0031, "Msg unpack failed"),
    (0x0032, "Msg no msg"),
    (0x0033, "Msg underflow"),
    (0x0034, "Msg overflow"),
    (0x0035, "Msg callback failed"),
    (0x0036, "Action cancelled"),
    (0x0037, "Object gone"),
    (0x0038, "No object"),
    (0x0039, "Can't get there"),
    (0x003a, "Dead"),
    (0x003b, "I left the world"),
    (0x003c, "I teleported"),
    (0x003d, "You charged too far"),
    (0x003e, "You are too tired to do that"),
    (0x003f, "Can't crouch in combat"),
    (0x0040, "Can't sit in combat"),
    (0x0041, "Can't lie down in combat"),
    (0x0042, "Can't chat emote in combat"),
    (0x0043, "No mtable data"),
    (0x0044, "Can't chat emote not standing"),
    (0x0045, "Too many actions"),
    (0x0046, "Hidden"),
    (0x0047, "General movement failure"),
    (0x0048, "You can't jump from this position"),
    (0x0049, "Can't jump loaded down"),
    (0x004a, "You killed yourself"),
    (0x004b, "Msg response failure"),
    (0x004c, "Object is static"),
    (0x004d, "Invalid PK status"),
    (0x03e9, "Invalid XP amount"),
    (0x03ea, "Invalid pp calculation"),
    (0x03eb, "Invalid cp calculation"),
    (0x03ec, "Unhandled stat answer"),
    (0x03ed, "Heart attack"),
    (0x03ee, "The container is closed"),
    (0x03f0, "Invalid inventory location"),
    (0x03f1, "Change combat mode failure"),
    (0x03f2, "Full inventory location"),
    (0x03f3, "Conflicting inventory location"),
    (0x03f4, "Item not pending"),
    (0x03f5, "Be wielded failure"),
    (0x03f6, "Be dropped failure"),
    (0x03f7, "You are too fatigued to attack"),
    (0x03f8, "You are out of ammunition"),
    (0x03f9, "Your attack misfired"),
    (0x03fa, "Youve attempted an impossible spell path"),
    (0x03fb, "Magic incomplete anim list"),
    (0x03fc, "Magic invalid spell type"),
    (0x03fd, "Magic inq position and velocity failure"),
    (0x03fe, "You don't know that spell"),
    (0x03ff, "Incorrect target type"),
    (0x0400, "You don't have all the components"),
    (0x0401, "You don't have enough mana to cast"),
    (0x0402, "Your spell fizzled"),
    (0x0403, "Your spell target is missing"),
    (0x0404, "Your projectile spell mislaunched"),
    (0x0405, "Magic spellbook add spell failure"),
    (0x0406, "Magic target out of range"),
    (0x0407, "Your spell cannot be cast outside"),
    (0x0408, "Your spell cannot be cast inside"),
    (0x0409, "Magic general failure"),
    (0x040a, "You are unprepared to cast a spell"),
    (0x040b, "Youve already sworn allegiance"),
    (0x040c, "Can't swear allegiance insufficient XP"),
    (0x040d, "Allegiance ignoring requests"),
    (0x040e, "Allegiance squelched"),
    (0x040f, "Allegiance max distance exceeded"),
    (0x0410, "Allegiance illegal level"),
    (0x0411, "Allegiance bad creation"),
    (0x0412, "Allegiance patron busy"),
    (0x0414, "You are not in allegiance"),
    (0x0415, "Allegiance remove hierarchy failure"),
    (0x0417, "Fellowship ignoring requests"),
    (0x0418, "Fellowship squelched"),
    (0x0419, "Fellowship max distance exceeded"),
    (0x041a, "Fellowship member"),
    (0x041b, "Fellowship illegal level"),
    (0x041c, "Fellowship recruit busy"),
    (0x041d, "You must be leader of fellowship"),
    (0x041e, "Your fellowship is full"),
    (0x041f, "Fellowship name is not permitted"),
    (0x0420, "Level too low"),
    (0x0421, "Level too high"),
    (0x0422, "That channel doesn't exist"),
    (0x0423, "You can't use that channel"),
    (0x0424, "You are already on that channel"),
    (0x0425, "You are not on that channel"),
    (0x0426, "Attuned item"),
    (0x0427, "You cannot merge different stacks"),
    (0x0428, "You cannot merge enchanted items"),
    (0x0429, "You must control at least one stack"),
    (0x042a, "Currently attacking"),
    (0x042b, "Missile attack not ok"),
    (0x042c, "Target not acquired"),
    (0x042d, "Impossible shot"),
    (0x042e, "Bad weapon skill"),
    (0x042f, "Unwield failure"),
    (0x0430, "Launch failure"),
    (0x0431, "Reload failure"),
    (0x0432, "Unable to make craft req"),
    (0x0433, "Craft animation failed"),
    (0x0434, "You can't craft with that number of items"),
    (0x0435, "Craft general error ui msg"),
    (0x0436, "Craft general error no ui msg"),
    (0x0437, "You do not pass crafting requirements"),
    (0x0438, "You do not have all the necessary items"),
    (0x0439, "Not all the items are available"),
    (0x043a, "You must be in peace mode to trade"),
    (0x043b, "You are not trained in that trade skill"),
    (0x043c, "Your hands must be free"),
    (0x043d, "You cannot link to that portal"),
    (0x043e, "You have solved this quest too recently"),
    (0x043f, "You have solved this quest too many times"),
    (0x0440, "Quest unknown"),
    (0x0441, "Quest table corrupt"),
    (0x0442, "Quest bad"),
    (0x0443, "Quest duplicate"),
    (0x0444, "Quest unsolved"),
    (0x0445, "Item requires quest to be picked up"),
    (0x0446, "Quest solved too long ago"),
    (0x044c, "Trade ignoring requests"),
    (0x044d, "Trade squelched"),
    (0x044e, "Trade max distance exceeded"),
    (0x044f, "Trade already trading"),
    (0x0450, "Trade busy"),
    (0x0451, "Trade closed"),
    (0x0452, "Trade expired"),
    (0x0453, "Trade item being traded"),
    (0x0454, "Trade non empty container"),
    (0x0455, "Trade non combat mode"),
    (0x0456, "Trade incomplete"),
    (0x0457, "Trade stamp mismatch"),
    (0x0458, "Trade unopened"),
    (0x0459, "Trade empty"),
    (0x045a, "Trade already accepted"),
    (0x045b, "Trade out of sync"),
    (0x045c, "P ks may not use portal"),
    (0x045d, "Non p ks may not use portal"),
    (0x045e, "House abandoned"),
    (0x045f, "House evicted"),
    (0x0460, "House already owned"),
    (0x0461, "House buy failed"),
    (0x0462, "House rent failed"),
    (0x0463, "Hooked"),
    (0x0465, "Magic invalid position"),
    (0x0466, "You must have dark majesty to use portal"),
    (0x0467, "Invalid ammo type"),
    (0x0468, "Skill too low"),
    (0x0469, "You have used all the hooks"),
    (0x046a, "Trade AI doesn't want"),
    (0x046b, "Hook house not owned"),
    (0x0474, "You must complete quest to use portal"),
    (0x047e, "House no allegiance"),
    (0x047f, "You must own house to use command"),
    (0x0480, "Your monarch does not own a mansion or villa"),
    (0x0481, "Your monarchs house is not a mansion or villa"),
    (0x0482, "Your monarch has closed the mansion"),
    (0x048a, "You must be monarch to purchase dwelling"),
    (0x048d, "Allegiance timeout"),
    (0x048e, "Your offer of allegiance was ignored"),
    (0x048f, "Confirmation in progress"),
    (0x0490, "You must be a monarch to use command"),
    (0x0491, "You must specify character to boot"),
    (0x0492, "You can't boot yourself"),
    (0x0493, "That character does not exist"),
    (0x0494, "That person is not in your allegiance"),
    (0x0495, "Can't break from patron not in allegiance"),
    (0x0496, "Your allegiance has been dissolved"),
    (0x0497, "Your patrons allegiance has been broken"),
    (0x0498, "You have moved too far"),
    (0x0499, "Tele to invalid position"),
    (0x049a, "Must have dark majesty to use"),
    (0x049b, "You fail to link with lifestone"),
    (0x049c, "You wandered too far to link with lifestone"),
    (0x049d, "You successfully link with lifestone"),
    (0x049e, "You must link to lifestone to recall"),
    (0x049f, "You fail to recall to lifestone"),
    (0x04a0, "You fail to link with portal"),
    (0x04a1, "You successfully link with portal"),
    (0x04a2, "You fail to recall to portal"),
    (0x04a3, "You must link to portal to recall"),
    (0x04a4, "You fail to summon portal"),
    (0x04a5, "You must link to portal to summon it"),
    (0x04a6, "You fail to teleport"),
    (0x04a7, "You have been teleported too recently"),
    (0x04a8, "You must be an advocate to use portal"),
    (0x04a9, "Portal ais not allowed"),
    (0x04aa, "Players may not use portal"),
    (0x04ab, "You are not powerful enough to use portal"),
    (0x04ac, "You are too powerful to use portal"),
    (0x04ad, "You cannot recall portal"),
    (0x04ae, "You cannot summon portal"),
    (0x04af, "Lock already unlocked"),
    (0x04b0, "You cannot lock or unlock that"),
    (0x04b1, "You cannot lock what is open"),
    (0x04b2, "Key doesn't fit this lock"),
    (0x04b3, "Lock used too recently"),
    (0x04b4, "You aren't trained in lockpicking"),
    (0x04b5, "Allegiance info empty name"),
    (0x04b6, "Allegiance info self"),
    (0x04b7, "Allegiance info too recent"),
    (0x04b8, "Abuse no such character"),
    (0x04b9, "Abuse reported self"),
    (0x04ba, "Abuse complaint handled"),
    (0x04bd, "You do not own that salvage tool"),
    (0x04be, "You do not own that item"),
    (0x04c1, "Material cannot be created"),
    (0x04c2, "Items attempting to salvage is invalid"),
    (0x04c3, "You cannot salvage items in trading"),
    (0x04c4, "You must be house guest to use portal"),
    (0x04c5, "Your allegiance rank is too low to use magic"),
    (0x04c7, "Your arcane lore is too low to use magic"),
    (0x04c8, "Item doesn't have enough mana"),
    (0x04cc, "You have been in PK battle too recently"),
    (0x04cd, "Trade AI refuse emote"),
    (0x04d0, "You fail to alter skill"),
    (0x04db, "Fellowship declined"),
    (0x04dc, "Fellowship timeout"),
    (0x04dd, "You have failed to alter attributes"),
    (0x04e0, "Cannot transfer attributes while wielding item"),
    (0x04e1, "You have succeeded transferring attributes"),
    (0x04e2, "Hook is duplicated"),
    (0x04e3, "Item is wrong type for hook"),
    (0x04e4, "Housing chest is duplicated"),
    (0x04e5, "Hook will be deleted"),
    (0x04e6, "Housing chest will be deleted"),
    (0x04e7, "Cannot swear allegiance while owning mansion"),
    (0x04eb, "You can't do that while in the air"),
    (0x04ec, "Cannot change PK status while recovering"),
    (0x04ed, "Advocates cannot change PK status"),
    (0x04ee, "Level too low to change PK status with object"),
    (0x04ef, "Level too high to change PK status with object"),
    (0x04f0, "You feel a harsh dissonance"),
    (0x04f1, "You are PK again"),
    (0x04f2, "You are temporarily no longer PK"),
    (0x04f3, "PK lite may not use portal"),
    (0x04fc, "You aren't trained in healing"),
    (0x04fd, "You don't own that healing kit"),
    (0x04fe, "You can't heal that"),
    (0x0500, "You aren't ready to heal"),
    (0x0501, "You can only heal players"),
    (0x0502, "Lifestone magic protects you"),
    (0x0503, "Portal energy protects you"),
    (0x0504, "You are non PK again"),
    (0x0505, "You're too close to your sanctuary"),
    (0x0506, "Can't do that trade in progress"),
    (0x0507, "Only non p ks may enter PK lite"),
    (0x0508, "You are now PK lite"),
    (0x050f, "You do not belong to a fellowship"),
    (0x0511, "Using max hooks silent"),
    (0x0512, "You are now using max hooks"),
    (0x0513, "You are no longer using max hooks"),
    (0x0516, "You are not permitted to use that hook"),
    (0x0519, "Locked fellowship cannot recruit you"),
    (0x051a, "Activation not allowed not owner"),
    (0x051d, "Turbine chat is enabled"),
    (0x0520, "You cannot add people to hear list"),
    (0x0523, "You are now deaf to {} screams"),
    (0x0524, "You can hear all players once again"),
    (0x0526, "You chicken out"),
    (0x0527, "You can possibly succeed"),
    (0x0528, "Fellowship is locked"),
    (0x0529, "Trade complete"),
    (0x052a, "Not a salvage tool"),
    (0x052b, "Character not available"),
    (0x0532, "You must wait to purchase house"),
    (0x0535, "You do not have authority in allegiance"),
    (0x0540, "You have max accounts banned"),
    (0x0545, "You have max allegiance officers"),
    (0x0546, "Your allegiance officers have been cleared"),
    (0x0548, "You cannot join channels while gagged"),
    (0x054a, "You are no longer allegiance officer"),
    (0x054c, "Your allegiance does not have hometown"),
    (0x054e, "Hook item not usable {} cannot open"),
    (0x054f, "Hook item not usable {} can open"),
    (0x0550, "Missile out of range"),
    (0x0552, "Must purchase throne of destiny to use function"),
    (0x0553, "Must purchase throne of destiny to use item"),
    (0x0554, "Must purchase throne of destiny to use portal"),
    (0x0555, "Must purchase throne of destiny to access quest"),
    (0x0556, "You failed to complete augmentation"),
    (0x0557, "Augmentation used too many times"),
    (0x0558, "Augmentation type used too many times"),
    (0x0559, "Augmentation not enough experience"),
    (0x055d, "Exit training academy to use command"),
    (0x055f, "Only p ks may use command"),
    (0x0560, "Only PK lite may use command"),
    (0x0561, "Max friends exceeded"),
    (0x0563, "That character not on your friends list"),
    (0x0564, "Only house owner can use command"),
    (0x0565, "Invalid allegiance name can't be empty"),
    (0x0566, "Invalid allegiance name too long"),
    (0x0567, "Invalid allegiance name bad characters"),
    (0x0568, "Invalid allegiance name inappropriate"),
    (0x0569, "Invalid allegiance name already in use"),
    (0x056b, "Allegiance name cleared"),
    (0x056c, "Invalid allegiance name same name"),
    (0x056f, "Invalid officer level"),
    (0x0570, "Allegiance officer title is not appropriate"),
    (0x0571, "Allegiance name is too long"),
    (0x0572, "Allegiance officer titles cleared"),
    (0x0573, "Allegiance title has illegal chars"),
    (0x0579, "You have not pre approved vassals"),
    (0x057c, "You have cleared pre approved vassal"),
    (0x057d, "Char is already gagged"),
    (0x057e, "Char is not currently gagged"),
    (0x0581, "Your allegiance chat privileges restored"),
    (0x0584, "Too many unique items"),
    (0x0585, "Heritage requires specific armor"),
    (0x0586, "Armor requires specific heritage"),
    (0x0587, "Olthoi cannot interact with that"),
    (0x0588, "Olthoi cannot use lifestones"),
    (0x0589, "Olthoi vendor looks in horror"),
    (0x058b, "Olthoi cannot join fellowship"),
    (0x058c, "Olthoi cannot join allegiance"),
    (0x058d, "You cannot use that item"),
    (0x058e, "This person will not interact with you"),
    (0x058f, "Only olthoi may use portal"),
    (0x0590, "Olthoi may not use portal"),
    (0x0591, "You may not use portal with vitae"),
    (0x0592, "You must be two weeks old to use portal"),
    (0x0593, "Olthoi can only recall to lifestone"),
    (0x0594, "Contract error"),
];

static WITH: [(u32, &str); 113] = [
    (0x001e, "{} is too busy to accept gifts"),
    (0x002b, "{} cannot carry anymore"),
    (0x004e, "You fail to affect {} you cannot affect anyone"),
    (0x004f, "You fail to affect {} they cannot be harmed"),
    (0x0050, "You fail to affect {} with beneficial spells"),
    (0x0051, "You fail to affect {} you are not PK"),
    (0x0052, "You fail to affect {} they are not PK"),
    (0x0053, "You fail to affect {} not same PK type"),
    (0x0054, "You fail to affect {} across house boundary"),
    (0x03ef, "{} is not accepting gifts right now"),
    (0x0413, "{} is already one of your followers"),
    (0x0416, "{} cannot have any more vassals"),
    (0x046a, "{} doesn't know what to do with that"),
    (0x0488, "You must be above level {} to buy house"),
    (0x0489, "You must be at or below level {} to buy house"),
    (0x048b, "You must be above allegiance rank {} to buy house"),
    (
        0x048c,
        "You must be at or below allegiance rank {} to buy house",
    ),
    (0x04bf, "The {} was not suitable for salvaging"),
    (0x04c0, "The {} containse the wrong material"),
    (0x04c6, "You must be {} to use item magic"),
    (0x04c9, "Your {} is too low to use item magic"),
    (0x04ca, "Only {} may use item magic"),
    (0x04cb, "You must specialize {} to use item magic"),
    (0x04ce, "AI refuse item during emote"),
    (0x04cf, "{} cannot accept stacked items"),
    (0x04d1, "Your {} skill must be trained"),
    (0x04d2, "Not enough skill credits to specialize"),
    (0x04d3, "Too much XP to recover from skill"),
    (0x04d4, "Your {} skill is already untrained"),
    (0x04d5, "Cannot lower skill while wielding item"),
    (0x04d6, "You have succeeded specializing {} skill"),
    (0x04d7, "You have succeeded unspecializing {} skill"),
    (0x04d8, "You have succeeded untraining {} skill"),
    (0x04d9, "Cannot untrain {} skill but recovered XP"),
    (0x04da, "Too many credits in specialized skills"),
    (0x04de, "Attribute transfer from too low"),
    (0x04df, "Attribute transfer to too high"),
    (0x04e8, "Item unusable on hook {} cannot open"),
    (0x04e9, "Item unusable on hook {} can open"),
    (0x04ea, "Item only usable on hook"),
    (
        0x04f4,
        "{} fails to affect you {} they cannot affect anyone",
    ),
    (0x04f5, "{} fails to affect you {} you cannot be harmed"),
    (0x04f6, "{} fails to affect you {} they are not PK"),
    (0x04f7, "{} fails to affect you {} you are not PK"),
    (0x04f8, "{} fails to affect you {} not same PK type"),
    (0x04f9, "{} fails to affect you across house boundary"),
    (0x04fa, "{} is an invalid target"),
    (0x04fb, "You are invalid target for spell of {}"),
    (0x04ff, "{} is at full health"),
    (0x0509, "{} has no spell targets"),
    (0x050a, "You have no targets for spell of {}"),
    (0x050b, "{} is now open fellowship"),
    (0x050c, "{} is now closed fellowship"),
    (0x050d, "{} is now leader of fellowship"),
    (0x050e, "You have passed fellowship leadership to {}"),
    (0x0510, "Max number of {} hooked"),
    (0x0514, "Max number of {} hooked until one is removed"),
    (0x0515, "No longer max number of {} hooked"),
    (0x0517, "{} is not close enough to your level"),
    (0x0518, "Locked fellowship cannot recruit {}"),
    (0x051b, "You have entered the {} channel"),
    (0x051c, "You have left the {} channel"),
    (0x051e, "{} will not receive message"),
    (0x051f, "Message blocked {}"),
    (0x0521, "{} has been added to hear list"),
    (0x0522, "{} has been removed from hear list"),
    (0x0525, "Fail to remove {} from loud list"),
    (0x0528, "You cannot open locked fellowship"),
    (0x052c, "You are now snooping on {}"),
    (0x052d, "You are no longer snooping on {}"),
    (0x052e, "You fail to snoop on {}"),
    (0x052f, "{} attempted to snoop on you"),
    (0x0530, "{} is already being snooped on"),
    (0x0531, "{} is in limbo"),
    (0x0533, "You have been booted from allegiance chat"),
    (0x0534, "{} has been booted from allegiance chat"),
    (0x0536, "Account of {} is already banned from allegiance"),
    (0x0537, "Account of {} is not banned from allegiance"),
    (0x0538, "Account of {} was not unbanned from allegiance"),
    (0x0539, "Account of {} is banned from allegiance"),
    (0x053a, "Account of {} is unbanned from allegiance"),
    (0x053b, "List of banned characters"),
    (0x053e, "{} is banned from allegiance"),
    (0x053f, "You are banned from allegiance"),
    (0x0541, "{} is now allegiance officer"),
    (0x0542, "Error setting {} as allegiance officer"),
    (0x0543, "{} is no longer allegiance officer"),
    (0x0544, "Error removing {} as allegiance o fficer"),
    (0x0547, "You must wait {} before communicating"),
    (0x0549, "Your allegiance officer status changed"),
    (0x054b, "{} is already allegiance officer of that level"),
    (0x054d, "The {} is currently in use"),
    (0x0551, "You are not listening to {} channel"),
    (0x055a, "Augmentation skill not trained"),
    (0x055b, "You succeded acquiring augmentation"),
    (
        0x055c,
        "You succeeded recovering XP from skill {} augmentation not untrainable",
    ),
    (0x055e, "AFK"),
    (0x0562, "{} is already on your friends list"),
    (
        0x056a,
        "You may only change allegiance name once every24 hours",
    ),
    (
        0x056d,
        "{} is the monarch and cannot be promoted or demoted",
    ),
    (
        0x056e,
        "That level of allegiance officer is now known as {}",
    ),
    (0x0574, "Your allegiance is currently {}"),
    (0x0575, "Your allegiance is now {}"),
    (
        0x0576,
        "You cannot accept allegiance {} your allegiance is locked",
    ),
    (
        0x0577,
        "You cannot swear allegiance {} allegiance of {} is locked",
    ),
    (0x0578, "You have pre approved {} to join allegiance"),
    (0x057a, "{} is already member of your allegiance"),
    (0x057b, "{} has been pre approved to join your allegiance"),
    (0x057f, "Your allegiance chat privileges removed"),
    (0x0580, "{} is temporarily gagged in allegiance chat"),
    (0x0582, "Your allegiance chat privileges restored by {}"),
    (0x0583, "You restore allegiance chat privileges to {}"),
    (0x058a, "{} cowers from you"),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_codes_read_well() {
        assert_eq!(text(0x001D), Some("You're too busy"));
        assert_eq!(text(0x0402), Some("Your spell fizzled"));
        assert_eq!(
            text_with(0x04FF, "Bob").as_deref(),
            Some("Bob is at full health")
        );
        assert!(text(0xFFFF_FFFF).is_none());
    }

    #[test]
    fn every_fellowship_refusal_ace_sends_as_a_code_has_text() {
        // The refusals founding and recruiting can meet as codes (ACE
        // `Entity/Fellowship.cs`, `Player_Fellowship.cs`); the two that
        // come as chat are read by their words instead.
        for code in [
            0x041d, 0x041e, 0x0519, 0x0528, 0x050f, 0x058b, 0x04db, 0x04dc,
        ] {
            assert!(text(code).is_some(), "no text for {code:#06x}");
        }
        assert_eq!(
            text_with(0x0518, "Bob").as_deref(),
            Some("Locked fellowship cannot recruit Bob")
        );
    }
}
